version: '3'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        author: YU
    image: test:0.1
    container_name: sky
    restart: always
    privileged: true
    network_mode: host
    devices:
      - /dev/ttyTHS0:/dev/ttyTHS0
    volumes:
      - ./config.ini:/config.ini
#    command: /bin/bash -c "./build/debug/demo"
    command: /bin/bash -c "./build/debug-nnx/demo"
#    command: /bin/bash -c "cd ./build/debug/ && make -j9 && cd - &&./build/debug/demo"
    stdin_open: true