version: '3'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        author: YU
    image: test:0.1
    container_name: sky
    restart: always
    privileged: true
    network_mode: host
    devices:
      - /dev/ttyTHS0:/dev/ttyTHS0
    volumes:
      - ./config.ini:/config.ini
    command: /bin/bash -c "./start.sh &&./build/debug/demo"
    stdin_open: true