//
// Created by 17273 on 2024/3/22.
//

#ifndef DEMO_YU_VOFA_H
#define DEMO_YU_VOFA_H

#include "YU_THREAD.h"
#include "YU_MOTOR.h"


void YU_F_VOFA_PARSE(YU_TYPEDEF_RECV_UNION *RECV);
void YU_F_VOFA_DEBUG_CAL(YU_TYPEDEF_DEBUG *DEBUG, YU_TYPEDEF_MOTOR *MOTOR);
void YU_F_VOFA_DEBUG();
void YU_F_VOFA_ASSIGN(YU_TYPEDEF_RECV_UNION *RECV);



#endif //DEMO_YU_VOFA_H
